### ISSUE TITLE
"Face Top Die" items missing tags

### ISSUE THREAD

**Issue by JotredDev** [redstoneguy10ls/lithiccoins#11]
All "Face Top Die" items are missing the "#lithiccoins:top_dies" tags, making it impossible to insert them into the coin mint.

I'm not experienced with modding, but I assume it's because of the .json files in [here](https://github.com/redstoneguy10ls/lithiccoins/tree/master/src/main/resources/data/lithiccoins/tags/items/top_dies)?

**Comment by redstoneguy10ls** [comment]
of course it is cause why would I tag shit properly

**Comment by redstoneguy10ls** [comment]
fixed as of commit ac96e40
