### ISSUE TITLE
'Heartbreak' dies displaying the 'Heart' preview in tooltip

### ISSUE THREAD

**Issue by JotredDev** [redstoneguy10ls/lithiccoins#13]
The 'Heartbreak' dies are displaying the preview for 'Heart' in their tooltips
![grafik](https://github.com/user-attachments/assets/c6453491-92dd-4c2f-964f-ddc8bce1f2ac)

I suspect it's due to [public static stampTypes getStamptype(Item item)](https://github.com/redstoneguy10ls/lithiccoins/blob/master/src/main/java/com/redstoneguy10ls/lithiccoins/util/LCHelpers.java) doing just a simple check if a given String is contained within an element of the stampTypes enum, which probably is checking the 'Heart' String first, finding it contained inside the String 'Heartbreak' and thus returning an incorrect value.

**Comment by redstoneguy10ls** [comment]
i thought i fixed this mother fucker (im not mad at you im mad at the code)
